 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
    executor:
      name: win/default     
    working_directory: C:\Users\circleci\project\AutoTranslate
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "autotranslate.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\AutoTranslate\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "autotranslate.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\autotranslate.exe 
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\autotranslate.exe
